# Generated by Django 6.1.1 on 2026-09-04 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام ستون')),
                ('data_type', models.CharField(max_length=255, verbose_name='نوع ستون')),
            ],
            options={
                'verbose_name': 'ستون',
                'verbose_name_plural': 'ستون ها',
                'db_table': 'column_table',
            },
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='datasets/', verbose_name='فایل دیتاست')),
                ('record_count', models.PositiveIntegerField(default=0, verbose_name='تعداد رکوردها')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
            ],
            options={
                'verbose_name': 'دیتاست',
                'verbose_name_plural': 'دیتاست ها',
                'db_table': 'dataset_table',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام پروژه')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه ها',
                'db_table': 'project_table',
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean', models.FloatField(blank=True, null=True, verbose_name='میانگین')),
                ('median', models.FloatField(blank=True, null=True, verbose_name='میانه')),
                ('mode', models.CharField(blank=True, max_length=255, null=True, verbose_name='مد')),
                ('value_counts', models.PositiveIntegerField(default=0, verbose_name='تعداد یونیک')),
                ('visualization', models.ImageField(blank=True, null=True, upload_to='visualizations/', verbose_name='تجسمی سازی')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='analysis_module.column', verbose_name='تحلیل')),
            ],
            options={
                'verbose_name': 'تحلیل',
                'verbose_name_plural': 'تحلیل ها',
                'db_table': 'analysis_table',
            },
        ),
        migrations.AddField(
            model_name='column',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='analysis_module.dataset', verbose_name='دیتاست'),
        ),
    ]
