# Generated by Django 6.1.1 on 2026-09-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_module', '0003_dataset_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
