# Generated by Django manual migration

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis_module', '0008_dataset_status_error_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='گفتگوی جدید', max_length=255, verbose_name='عنوان گفتگو')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='analysis_module.project', verbose_name='پروژه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نشست گفتگو',
                'verbose_name_plural': 'نشست‌های گفتگو',
                'db_table': 'chat_session_table',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'کاربر'), ('assistant', 'دستیار'), ('system', 'سیستم')], default='user', max_length=20, verbose_name='فرستنده')),
                ('content', models.TextField(verbose_name='متن پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat_module.chatsession', verbose_name='نشست گفتگو')),
            ],
            options={
                'verbose_name': 'پیام گفتگو',
                'verbose_name_plural': 'پیام‌های گفتگو',
                'db_table': 'chat_message_table',
                'ordering': ['created_at'],
            },
        ),
    ]
